### ISSUE TITLE
Button events not registering

### ISSUE THREAD

**Issue by Tengyyy** [IcarusCoding/WindowsTaskbar#1] opened 2022-11-17 14:08 UTC
I'm trying to add taskbar buttons to a JavaFX stage

With the following code the 2 buttons get added to the taskbar but the button click events are not being registered. 
`
var handle = WindowHandleFinder.getFromActiveWindow();

        IWindowsTaskbar taskbar = TaskbarBuilder.builder()
                .autoInit()
                .setHWnd(handle)
                .addButtons(TaskbarButtonListBuilder.builder()
                        .buttonBuilder()
                        .withFlag(TaskbarButtonFlag.ENABLED)
                        .setOnClicked((TaskbarButtonClickEvent e) -> System.out.println("test"))
                        .build()
                        .buttonBuilder()
                        .withFlag(TaskbarButtonFlag.DISABLED)
                        .build()
                        .build())
                .build();`

Also if I call overrideWndProc() like in the sample code, the entire stage becomes unresponsive and I can't even close it.

I also tried passing in the javafx stage in the constructor and calling WindowHandleFinder.getFromInternalJavaFX(stage), but then I got this error:
Unable to make com.sun.javafx.tk.TKStage javafx.stage.Window.getPeer() accessible: module javafx.graphics does not "opens javafx.stage" to module win.taskbar

I would really appreciate your help on this

**Comment by IcarusCoding** [comment] 2022-12-17 13:33
If you call ``overrideWndProc`` use need to keep a reference to the ``IWindowTaskbar`` object, because internally the message loop of the native window is redirect to a custom one. This redirection does not work if the JVM garbage collector is removing the taskbar object. If the message loop is overridden and the garbage collector removes the taskbar object, the JavaFX stage becomes fully unresponsive like you described.
Here is an example to prevent that from happening:
```java
public final class App extends Application {

    private IWindowTaskbar taskbar; // strong reference

    @Override
    public void start(Stage primaryStage) {
        this.taskbar = TaskbarBuilder.builder()
                .setHWnd(WindowHandleFinder.getFromInternalJavaFX(stage))
                .autoInit()
                .overrideWndProc()
                .addButtons(ToolbarButtonListBuilder.builder()
                        .buttonBuilder()
                        .setIcon(testIcon)
                        .setTooltip("Click Me")
                        .withFlag(TaskbarButtonFlag.ENABLED)
                        .setOnClicked(evt -> System.out.println("Clicked on button with id " + evt.id()))
                        .build()
                        .buttonBuilder()
                        .setIcon(testIcon)
                        .setTooltip("Test Tooltip")
                        .withFlag(TaskbarButtonFlag.ENABLED)
                        .withFlag(TaskbarButtonFlag.DISMISS_ON_CLICK)
                        .build()
                        .build())
                .build();
        // ...
    }

}
```
Your second issue is related to the Java Jigsaw module system. The ``win.taskbar`` module is not able to access the JavaFX modules. You should be able to fix that with correctly added ``--add-opens`` directives to your JVM arguments. If you cannot resolve that problem, please feel free to reply to this issue and I will happily help you.

**Comment by Tengyyy** [comment] 2022-12-18 23:05
Keeping a strong reference to the taskbar fixed my issue, thanks.
I was also wondering if its possible to change button flags after it has already been created, for example disable a button.
I also noticed that button icons dont update while im hovering over the taskbar, but I instead have to leave the taskbar and reopen it for changes to take effect.

**Comment by IcarusCoding** [comment] 2022-12-19 21:08
Hi,
I just added the functionality to update the flags. I also added a convenience method for the enabled/disabled state.
For example, this button switches to disabled on the first click:

```java
ToolbarButtonListBuilder.builder()
                        .buttonBuilder()
                        .withFlag(TaskbarButtonFlag.ENABLED)
                        .setOnClicked(evt -> {
                            evt.button().setDisabled(true);
                            evt.taskbar().updateButton(evt.id());
                        });
```
If you want to switch other flags, you can use the ``TaskbarButton#setFlags`` method.
Keep in mind, that you need to save the ID of a button if you want to update them outside the click event handler.

Good luck & happy coding

**Comment by Tengyyy** [comment] 2022-12-20 01:27
Hey.
Wanted to point out this issue I found where the button icon only updates once we minimize the thumbnail

You can see in this video how the play/pause button icon doesnt update on click. However this should be possible because apps like Spotify and Windows Media Player etc do it correctly.

https://user-images.githubusercontent.com/69690923/208559060-5bb97269-7324-46ae-b8fd-140d75b77056.mp4

**Comment by IcarusCoding** [comment] 2023-08-12 15:21
Closing this as due to non reproducibility

**Closed as completed by IcarusCoding** 2023-08-12 15:21 UTC
